import { Zap } from 'lucide-react'
import type { Workspace } from '../../app/types'
import { Avatar, EmptyState } from '../../components/ui'
import { ValoTrackerSync } from './ValoTrackerSync'
import { LoginOptions, type LoginHandler } from '../auth/LoginOptions'

export function ProfilePage({ workspace, onLogin }: { workspace: Workspace | null; onLogin: LoginHandler }) {
  const profile = workspace?.profile
  const rank = workspace?.rank
  if (!workspace?.session) return <><section className="hero-heading"><div><p className="eyebrow">CUENTA</p><h1>Mi perfil</h1><p className="subtitle">Vincula Discord para buscar el jugador asociado a tu usuario de Supabase.</p></div><LoginOptions onLogin={onLogin} /></section><div className="card"><EmptyState title="Perfil privado" body="El perfil competitivo se consulta después de autenticarte. No se inventan datos de usuario." /></div></>
  if (!profile) return <><section className="hero-heading"><div><p className="eyebrow">CUENTA</p><h1>Perfil sin vincular</h1><p className="subtitle">La sesión está activa, pero players.auth_user_id no tiene una fila asociada.</p></div></section><div className="card"><EmptyState title="No se encontró un jugador asociado" body="Comprueba el vínculo de Discord y las políticas de lectura del proyecto. Esta aplicación no crea ni modifica perfiles." /></div></>
  const initials = (profile.display_name || profile.username).split(/\s+/).map((part) => part[0]).slice(0, 2).join('').toUpperCase()
  const total = rank?.wins != null && rank.losses != null ? rank.wins + rank.losses : null
  return <><section className="hero-heading"><div><p className="eyebrow">CUENTA</p><h1>Mi perfil</h1><p className="subtitle">Identidad competitiva asociada a tu cuenta de Discord.</p></div><span className="source-pill">Perfil real de Supabase</span></section><div className="profile-layout"><div className="profile-card card"><div className="profile-cover" /><div className="profile-main"><Avatar initials={initials} url={profile.avatar_url || undefined} /><div><h2>{profile.display_name || profile.username}{profile.verified && <span className="verified">✓</span>}</h2><p>@{profile.username}{profile.country ? ` · ${profile.country}` : ''}</p></div><span className="profile-status"><span className="online-dot" />Conectado</span></div><div className="profile-bio">{profile.bio || 'Este perfil no contiene una biografía.'}</div></div><div className="profile-side card"><p className="eyebrow">RANGO COMPETITIVO</p><div className="profile-rank"><div className="rank-emblem small"><Zap size={19} /></div><div><strong>{rank?.rank || 'Sin rango registrado'}</strong><span>{rank?.mmr != null ? `${rank.mmr.toLocaleString('es')} MMR` : 'MMR no disponible'}</span></div></div><div className="mini-stat-row"><span>{rank?.season || 'Temporada no disponible'}</span><strong>{rank?.placementDone ? 'Clasificado' : 'Sin clasificación'}</strong></div></div></div><div className="section-header"><div><p className="eyebrow">ESTADÍSTICAS</p><h2>Rendimiento registrado</h2></div></div><div className="stats-strip profile-stats"><div><span>PARTIDAS</span><strong>{total ?? '—'}</strong></div><div><span>VICTORIAS</span><strong className="text-green">{rank?.wins ?? '—'}</strong></div><div><span>DERROTAS</span><strong>{rank?.losses ?? '—'}</strong></div><div><span>REGIÓN</span><strong className="stat-caption">{profile.region || '—'}</strong></div></div><ValoTrackerSync riotHandle={profile.riot_handle} guildId={import.meta.env.VITE_DISCORD_GUILD_ID} channelId={import.meta.env.VITE_DISCORD_VALORANT_STATS_CHANNEL_ID} /></>
}
