import { useMemo, useState } from 'react'
import { Bell, ChevronDown, CircleHelp, Crown, Gamepad2, LayoutDashboard, LogOut, Menu, Moon, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Swords, Trophy, UserRound, Users, X, Zap } from 'lucide-react'
import './App.css'

type Page = 'dashboard' | 'matches' | 'tournaments' | 'profile' | 'settings'
type Match = { id: number; game: 'VALORANT' | 'CS2' | 'LoL'; mode: string; result: 'Victoria' | 'Derrota'; score: string; date: string; rating: string }
const matches: Match[] = [
  { id: 1, game: 'VALORANT', mode: 'Clasificatoria · Haven', result: 'Victoria', score: '13 — 9', date: 'Hoy, 18:42', rating: '+24 VP' },
  { id: 2, game: 'CS2', mode: 'Premier · Mirage', result: 'Victoria', score: '16 — 12', date: 'Ayer, 21:08', rating: '+18 VP' },
  { id: 3, game: 'VALORANT', mode: 'Scrim · Ascent', result: 'Derrota', score: '8 — 13', date: 'Ayer, 19:32', rating: '-11 VP' },
  { id: 4, game: 'LoL', mode: 'Ranked · Grieta', result: 'Victoria', score: '31:14', date: '26 Sep, 22:11', rating: '+21 VP' },
]
const tournaments = [
  { title: 'VANTCALL Open #04', game: 'VALORANT', teams: '64 / 128', prize: '500 €', status: 'Inscripciones abiertas', tone: 'red' },
  { title: 'Nocturna Premier', game: 'CS2', teams: '28 / 32', prize: '250 €', status: 'Empieza en 2 h', tone: 'purple' },
  { title: 'Clash de la comunidad', game: 'LoL', teams: '16 / 16', prize: '150 €', status: 'Llave publicada', tone: 'blue' },
]
const navItems: { id: Page; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'dashboard', label: 'Inicio', icon: LayoutDashboard }, { id: 'matches', label: 'Partidas', icon: Swords }, { id: 'tournaments', label: 'Torneos', icon: Trophy }, { id: 'profile', label: 'Mi perfil', icon: UserRound },
]
function GameBadge({ game }: { game: string }) { return <span className={`game-badge ${game.toLowerCase().replace(' ', '')}`}>{game}</span> }

function App() {
  const [page, setPage] = useState<Page>('dashboard'), [queueing, setQueueing] = useState(false), [notifications, setNotifications] = useState(false), [mobileOpen, setMobileOpen] = useState(false), [toast, setToast] = useState('')
  const pageTitle = useMemo(() => ({ dashboard: 'Resumen competitivo', matches: 'Historial de partidas', tournaments: 'Torneos activos', profile: 'Mi perfil', settings: 'Ajustes' })[page], [page])
  const navigate = (next: Page) => { setPage(next); setMobileOpen(false) }
  const startQueue = () => { setQueueing((current) => !current); setToast(queueing ? 'Has salido de la cola' : 'Buscando rival en VALORANT…'); window.setTimeout(() => setToast(''), 2800) }
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand-row"><div className="brand-mark">V</div><div><strong>VANTCALL</strong><span>DESKTOP</span></div><button className="icon-button close-mobile" onClick={() => setMobileOpen(false)} aria-label="Cerrar menú"><X size={18} /></button></div>
      <div className="profile-mini"><div className="avatar avatar-sm">NC</div><div className="profile-mini-copy"><strong>Nico Caster</strong><span><span className="online-dot" /> En línea</span></div><ChevronDown size={16} className="muted" /></div>
      <nav className="main-nav"><p className="nav-label">COMPETIR</p>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => navigate(id)}><Icon size={18} /><span>{label}</span>{id === 'matches' && <span className="nav-count">4</span>}</button>)}<p className="nav-label nav-spacer">CUENTA</p><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => navigate('settings')}><Settings size={18} /><span>Ajustes</span></button><button className="nav-item" onClick={() => setToast('Centro de ayuda próximamente')}><CircleHelp size={18} /><span>Ayuda</span></button></nav>
      <div className="sidebar-bottom"><div className="pro-card"><div className="pro-icon"><Crown size={18} /></div><div><strong>VANT Pro</strong><p>Desbloquea stats avanzadas</p></div><ChevronDown size={15} /></div><button className="nav-item logout" onClick={() => setToast('Sesión cerrada de forma segura')}><LogOut size={18} /><span>Cerrar sesión</span></button></div>
    </aside>
    <main className="main-content"><header className="topbar"><button className="icon-button menu-mobile" onClick={() => setMobileOpen(true)} aria-label="Abrir menú"><Menu size={20} /></button><div className="breadcrumb"><span>VANTCALL</span><span className="slash">/</span><strong>{pageTitle}</strong></div><div className="top-actions"><button className="icon-button" onClick={() => setNotifications((value) => !value)} aria-label="Notificaciones"><Bell size={19} /><span className="notification-dot" /></button><div className="top-avatar avatar">NC</div></div>{notifications && <div className="notification-popover"><strong>Notificaciones</strong><p><span className="notification-red" /> Tu partida ha sido registrada (+24 VP)</p><p><span className="notification-red" /> VANTCALL Open #04 cierra pronto</p></div>}</header>
      <div className="page-wrap">{page === 'dashboard' && <Dashboard queueing={queueing} startQueue={startQueue} navigate={navigate} />}{page === 'matches' && <MatchesPage />}{page === 'tournaments' && <TournamentsPage />}{page === 'profile' && <ProfilePage navigate={navigate} />}{page === 'settings' && <SettingsPage />}</div></main>{toast && <div className="toast"><span className="toast-check">✓</span>{toast}</div>}
  </div>
}
function Dashboard({ queueing, startQueue, navigate }: { queueing: boolean; startQueue: () => void; navigate: (page: Page) => void }) { return <><section className="hero-heading"><div><p className="eyebrow">MARTES, 29 DE SEPTIEMBRE DE 2026</p><h1>Buenas, Nico <span className="wave">✦</span></h1><p className="subtitle">Tu próxima victoria está a una cola de distancia.</p></div><button className="secondary-button"><Plus size={17} /> Invitar jugador</button></section><section className="dashboard-grid"><div className="rank-card card"><div className="card-heading"><div><p className="eyebrow">RANGO VANTS · VALORANT</p><h2>Escarlata <span className="rank-tier">III</span></h2></div><div className="rank-emblem"><Zap size={27} /></div></div><div className="rank-progress"><div className="progress-label"><span>1,284 VP</span><span>1,500 VP</span></div><div className="progress-track"><div className="progress-fill" /></div><p>216 VP para subir a <strong>Escarlata II</strong></p></div><div className="rank-footer"><span><span className="green-dot" /> +124 VP esta semana</span><button onClick={() => navigate('profile')}>Ver evolución <span>→</span></button></div></div><div className="queue-card card"><div className="card-heading"><div><p className="eyebrow">ENCONTRAR PARTIDA</p><h2>¿Listo para competir?</h2></div><Gamepad2 size={24} className="red-icon" /></div><p className="card-copy">Únete a una cola clasificatoria y demuestra tu nivel.</p><div className="queue-select"><GameBadge game="VALORANT" /><span>Clasificatoria · 5v5</span><ChevronDown size={16} /></div><button className={`primary-button ${queueing ? 'queueing' : ''}`} onClick={startQueue}><Swords size={18} />{queueing ? 'Salir de la cola' : 'Buscar partida'}<span>→</span></button><div className="queue-meta"><span><ShieldCheck size={14} /> Anti-cheat activo</span><span>~ 3 min</span></div></div></section><section className="section-header"><div><p className="eyebrow">ACTIVIDAD RECIENTE</p><h2>Últimas partidas</h2></div><button className="link-button" onClick={() => navigate('matches')}>Ver historial completo <span>→</span></button></section><div className="table-card card"><div className="table-head"><span>PARTIDA</span><span>RESULTADO</span><span>RATING</span><span>FECHA</span><span /></div>{matches.slice(0, 3).map((match) => <MatchRow key={match.id} match={match} />)}</div><section className="section-header tournament-header"><div><p className="eyebrow">NO TE LO PIERDAS</p><h2>Torneos para ti</h2></div><button className="link-button" onClick={() => navigate('tournaments')}>Explorar torneos <span>→</span></button></section><div className="tournament-grid">{tournaments.map((tournament) => <TournamentCard key={tournament.title} tournament={tournament} />)}</div></> }
function MatchRow({ match }: { match: Match }) { return <div className="table-row"><div className="match-cell"><div className={`game-square ${match.game.toLowerCase().replace(' ', '')}`}>{match.game === 'VALORANT' ? 'V' : match.game === 'CS2' ? 'C' : 'L'}</div><div><strong>{match.mode}</strong><span>{match.game}</span></div></div><div><span className={`result ${match.result === 'Victoria' ? 'win' : 'loss'}`}>{match.result}</span><strong className="score">{match.score}</strong></div><strong className={match.rating.startsWith('+') ? 'rating-positive' : 'rating-negative'}>{match.rating}</strong><span className="muted">{match.date}</span><button className="more-button"><MoreHorizontal size={18} /></button></div> }
function TournamentCard({ tournament }: { tournament: typeof tournaments[number] }) { return <article className="tournament-card card"><div className={`tournament-banner ${tournament.tone}`}><Gamepad2 size={27} /><span>{tournament.game}</span><button className="more-button"><MoreHorizontal size={18} /></button></div><div className="tournament-body"><span className="status-pill">{tournament.status}</span><h3>{tournament.title}</h3><div className="tournament-meta"><span><Users size={14} /> {tournament.teams} equipos</span><strong>{tournament.prize}</strong></div></div></article> }
function MatchesPage() { return <><section className="hero-heading"><div><p className="eyebrow">COMPETIR</p><h1>Historial de partidas</h1><p className="subtitle">Revisa tu rendimiento y evolución competitiva.</p></div><button className="secondary-button"><Search size={17} /> Buscar por mapa</button></section><div className="stats-strip"><div><span>PARTIDAS TOTALES</span><strong>148</strong></div><div><span>VICTORIAS</span><strong className="text-green">87</strong></div><div><span>WIN RATE</span><strong>58.8%</strong></div><div><span>VP ESTA TEMPORADA</span><strong className="text-red">+284</strong></div></div><div className="table-card card full-table"><div className="table-head"><span>PARTIDA</span><span>RESULTADO</span><span>RATING</span><span>FECHA</span><span /></div>{matches.map((match) => <MatchRow key={match.id} match={match} />)}</div></> }
function TournamentsPage() { return <><section className="hero-heading"><div><p className="eyebrow">COMPETIR</p><h1>Torneos activos</h1><p className="subtitle">Encuentra tu próximo desafío y compite por premios.</p></div><button className="primary-button compact"><Plus size={17} /> Crear torneo</button></section><div className="filter-row"><button className="filter active">Todos</button><button className="filter">VALORANT</button><button className="filter">CS2</button><button className="filter">League of Legends</button></div><div className="tournament-grid large">{tournaments.concat([{ title: 'Copa Escarlata', game: 'VALORANT', teams: '42 / 64', prize: '1,000 €', status: 'Abre mañana', tone: 'orange' }]).map((tournament) => <TournamentCard key={tournament.title} tournament={tournament} />)}</div></> }
function ProfilePage({ navigate }: { navigate: (page: Page) => void }) { return <><section className="hero-heading"><div><p className="eyebrow">CUENTA</p><h1>Mi perfil</h1><p className="subtitle">Tu identidad competitiva en VANTCALL.</p></div><button className="secondary-button" onClick={() => navigate('settings')}><Settings size={17} /> Editar perfil</button></section><div className="profile-layout"><div className="profile-card card"><div className="profile-cover" /><div className="profile-main"><div className="avatar avatar-lg">NC</div><div><h2>Nico Caster <span className="verified">✓</span></h2><p>@nicocaster · España</p></div><span className="profile-status"><span className="online-dot" /> Disponible para jugar</span></div><div className="profile-bio">Jugador competitivo y creador de contenido. Principalmente VALORANT y CS2.</div></div><div className="profile-side card"><p className="eyebrow">RANGO VANTS</p><div className="profile-rank"><div className="rank-emblem small"><Zap size={19} /></div><div><strong>Escarlata III</strong><span>1,284 VP</span></div></div><div className="mini-stat-row"><span>Temporada 0</span><strong>Top 8%</strong></div></div></div><div className="section-header"><div><p className="eyebrow">ESTADÍSTICAS</p><h2>Rendimiento global</h2></div></div><div className="stats-strip profile-stats"><div><span>PARTIDAS</span><strong>148</strong></div><div><span>WIN RATE</span><strong>58.8%</strong></div><div><span>KDA</span><strong>1.42</strong></div><div><span>MEJOR RACHA</span><strong>7</strong></div></div></> }
function SettingsPage() { return <><section className="hero-heading"><div><p className="eyebrow">CUENTA</p><h1>Ajustes</h1><p className="subtitle">Personaliza tu experiencia en VANTCALL Desktop.</p></div></section><div className="settings-card card"><div className="setting-row"><div><strong>Notificaciones de partida</strong><span>Recibe un aviso cuando encuentres rival o empiece un torneo.</span></div><button className="toggle on"><span /></button></div><div className="setting-row"><div><strong>Estado visible</strong><span>Permite que tus amigos vean si estás conectado.</span></div><button className="toggle on"><span /></button></div><div className="setting-row"><div><strong>Iniciar con el sistema</strong><span>Abre VANTCALL Desktop al encender tu equipo.</span></div><button className="toggle"><span /></button></div><div className="setting-row"><div><strong>Tema de la aplicación</strong><span>La interfaz oscura está optimizada para sesiones largas.</span></div><button className="theme-choice"><Moon size={15} /> Oscuro <ChevronDown size={14} /></button></div></div></> }
export default App
